version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-sm-api
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel


    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        ports:
            - 8080:8080

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql-sm-api
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: sm-api
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-sm-api
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel